# For local

version: '3.8'
services:
  tebu_be:
    container_name: tebu_be
    image: tebu_be:${TAG}
    build:
      context: .
      args:
        ENV: ENV
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - network
    links:
      - mongo
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/mongo
    networks:
      - network
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    restart: unless-stopped

volumes:
  mongodata:

networks:
  network:
    driver: bridge
