#docker-compose -f docker-compose-hub.yaml -d --build tebu_be

version: '3.8'
services:
  tebu_be:
    container_name: tebu_be
    image: nguyenbachtoan/tebu-nest:1.0.0-dev
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - network
    links:
      - mongo
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/mongo
    networks:
      - network
    ports:
      - '27017:27017'
    restart: unless-stopped

volumes:
  mongodata:

networks:
  network:
    driver: bridge
