name: Tebu CICD

on:
  push:
    branches: [test/cicd]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: ls -l

      - name: Create .env file
        run: |
          touch .env.dev
          echo TAG=${{ secrets.TAG }} >> .env.dev
          echo APP_PORT=${{ secrets.APP_PORT }} >> .env.dev
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env.dev
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env.dev

      - name: Copy .env file to source code
        run: cp .env.dev ./
      - name: Check Container
        run: docker ps -a
